# Generated by Django 5.0.2 on 2024-02-17 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0002_questiontype_created_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='body',
            new_name='question',
        ),
    ]
