# Generated by Django 5.0.2 on 2024-02-17 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0003_rename_body_question_question'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='question',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='questionoption',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='questionoption',
            name='updated_at',
        ),
    ]
