# Generated by Django 5.0.2 on 2024-02-17 18:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0004_remove_question_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveryformquestionanswer',
            name='chosen_answer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='selected_option', to='survey.questionoption'),
        ),
    ]
